# Service
apiVersion: v1
kind: Service
metadata:
  name: concord
  namespace: concord
  labels:
    app: concord
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: concord
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord
  namespace: concord
  labels:
    app: concord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concord
  template:
    metadata:
      labels:
        app: concord
    spec:
      containers:
        - image: DOCKER_REGISTRY/concord-db:latest
          name: db
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
              name: db-connection
              protocol: TCP
        - name: concord
          image: DOCKER_REGISTRY/concord:latest
          imagePullPolicy: Always
          command: ['/start-reload.sh']
          env:
            - name: PORT
              value: "80"
            - name: MODULE_NAME
              value: src.main
            - name: BACKEND_URL
              value: http://localhost:81
            - name: STARLETTE_BACKEND_URL
              value: http://starlette-backend.concord:8000
            - name: OPENFAAS_URL
              value: http://gateway.openfaas:8080
            - name: SQL_ALCHEMY_DB_URI
              value: postgresql://postgres:postgrespassword@localhost:5432/postgres
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONIOENCODING
              value: "UTF-8"
          ports:
            - name: api
              containerPort: 80
        - name: starlette-backend
          image: DOCKER_REGISTRY/starlette-backend:latest
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--workers", "4"]
          ports:
            - name: api
              containerPort: 8000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: concord-ingress
  namespace: concord
spec:
  prefix: /
  service: concord:80
  timeout_ms: 40000