default_language_version:
  python: python3.8
repos:
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 20.8b1
- hooks:
  - id: isort
    name: isort
  repo: https://github.com/timothycrosley/isort
  rev: 5.6.4
- hooks:
  - additional_dependencies: []
    files: ^backend/
    id: mypy
    name: mypy (server)
  - files: ^concord/
    id: mypy
    name: mypy (client)
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
