version: '3.8'
services:
  backend:
    networks: 
      - new
    build: backend
    volumes:
      - ./backend/src:/app/src/
    entrypoint: /start-reload.sh
    environment:
      PORT: "81"
      MODULE_NAME: src.main
    ports:
      - "81:80"
  concord:
    networks:
      - new
    build: concord
    volumes:
      - ./concord/src:/app/src/
    entrypoint: /start-reload.sh
    environment:
      MODULE_NAME: src.main
      BACKEND_URL: http://backend:81
    ports:
      - "80:80"

networks:
  new:
# volumes:
#   middleware:
#     source: ./middleware