version: '3.9'
services:
  starlette-backend:
    networks:
      - new
    image: localhost:5001/starlette-backend
    ports:
      - "5002:8000"
    volumes:
      - ./starlette-backend:/app
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--workers", "4"]
  concord:
    networks:
      - new
    image: localhost:5001/concord
    depends_on:
      - "postgres"
    volumes:
      - ./concord/src:/app/src/
      - ./concord/scripts/prestart.sh:/app/prestart.sh
      - ./concord/scripts/rundev.py:/app/rundev.py
    entrypoint: /start-reload.sh
    environment:
      SPACES_KEY: ${SPACES_KEY}
      SPACES_SECRET: ${SPACES_SECRET}
      MODULE_NAME: src.main
      OPENFAAS_URL: http://starlette-backend:8000
      STARLETTE_BACKEND_URL: http://starlette-backend:8000
      SQL_ALCHEMY_DB_URI: postgresql://postgres:postgrespassword@postgres:5432/postgres
      DB_PASSWORD: postgrespassword
      DB_HOST: postgres
    ports:
      - "80:80"
  postgres:
    networks: 
      - new
    image: localhost:5001/concord-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  graphql-engine:
    networks: 
      - new
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
networks:
  new:
# volumes:
#   middleware:
#     source: ./middleware