version: '3.8'
services:
  backend:
    networks: 
      - new
    build: backend
    volumes:
      - ./backend/src:/app
    entrypoint: /start.sh
    environment:
      WORKERS_PER_CORE: 2
    ports:
      - "8000:80"
  middleware:
    networks: 
      - new
    build: middleware
    volumes:
      - ./middleware/src:/app
    entrypoint: /start-reload.sh
    ports:
      - "8001:80"

networks:
  new:
# volumes:
#   middleware:
#     source: ./middleware