version: '3.8'
services:
  starlette-backend:
    networks:
      - new
    image: starlette
    ports:
      - "5001:8000"
    volumes:
      - ./starlette-backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--workers", "4"]
  backend:
    networks:
      - new
    build: backend
    volumes:
      - ./backend/src:/app/src/
    entrypoint: /start-reload.sh
    environment:
      PORT: "81"
      MODULE_NAME: src.main
    ports:
      - "81:81"
  concord:
    networks:
      - new
    build: concord
    volumes:
      - ./concord/src:/app/src/
      - ./concord/scripts/prestart.sh:/app/prestart.sh
      - ./concord/scripts/rundev.py:/app/rundev.py
    entrypoint: /start-reload.sh
    environment:
      MODULE_NAME: src.main
      BACKEND_URL: http://backend:81
      OPENFAAS_URL: http://of-backend:000
      STARLETTE_BACKEND_URL: http://starlette-backend:8000
      SQL_ALCHEMY_DB_URI: postgresql://postgres:postgrespassword@postgres:5432/postgres
    ports:
      - "80:80"
  postgres:
    volumes:
      - ./concord/src/flatData.csv:/flatData.csv
    networks: 
      - new
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  graphql-engine:
    networks: 
      - new
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
networks:
  new:
# volumes:
#   middleware:
#     source: ./middleware