version: '3.8'
services:
  backend:
    networks: 
      - new
    build: backend
    volumes:
      - ./backend/src:/app/src/
    entrypoint: /start-reload.sh
    environment:
      MODULE_NAME: src.main
    ports:
      - "8000:80"
  concord:
    networks:
      - new
    build: concord
    volumes:
      - ./concord/src:/app/src/
    entrypoint: /start-reload.sh
    environment:
      MODULE_NAME: src.main
      BACKEND_URL: http://backend:80
    ports:
      - "8001:81"

networks:
  new:
# volumes:
#   middleware:
#     source: ./middleware