version: '3.8'
services:
  backend:
    networks: 
      - new
    build: backend
    volumes:
      - ./backend/src:/app
    entrypoint: /start-reload.sh
    environment:
      WORKERS_PER_CORE: 1
    ports:
      - "8000:80"
  middleware:
    networks: 
      - new
    build: concord
    volumes:
      - ./concord/src:/app
    entrypoint: /start-reload.sh
    ports:
      - "8001:80"

networks:
  new:
# volumes:
#   middleware:
#     source: ./middleware