"""Test setup

Revision ID: ad4a74dcf82e
Revises: 26801bcfd223
Create Date: 2020-12-06 21:41:35.618624

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad4a74dcf82e"
down_revision = "26801bcfd223"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
