# Service
apiVersion: v1
kind: Service
metadata:
  name: concord
  namespace: concord
  labels:
    app: concord
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: 81
  selector:
    app: concord
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord
  namespace: concord
  labels:
    app: concord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concord
  template:
    metadata:
      labels:
        app: concord
    spec:
      containers:
        - name: concord
          image: localhost:5000/concord-fastapi_concord:latest
          command: ['/start-reload.sh']
          env:
            - name: PORT
              value: "81"
            - name: MODULE_NAME
              value: src.main
            - name: BACKEND_URL
              value: http://localhost:80
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONIOENCODING
              value: "UTF-8"
          ports:
          - name: api
            containerPort: 81
          volumeMounts:
            - name: local-repo
              mountPath: /app/src/
              subPath: concord/src/
              readOnly: true
        - name: backend
          image: localhost:5000/concord-fastapi_backend:latest
          command: ['/start-reload.sh']
          env:
            - name: MODULE_NAME
              value: src.main
          ports:
          - name: api
            containerPort: 80
          volumeMounts:
            - name: local-repo
              mountPath: /app/src/
              subPath: backend/src/
              readOnly: true
      volumes:
        - name: local-repo
          hostPath:
            path: /concord-fastapi
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: concord-ingress
#   namespace: concord
#   annotations:
#     kubernetes.io/ingress.class: ambassador
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           serviceName: concord
#           servicePort: 8001
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: concord-ingress
  namespace: concord
spec:
  prefix: /
  service: concord:8001
  timeout_ms: 40000