# Service
apiVersion: v1
kind: Service
metadata:
  name: concord
  namespace: concord
  labels:
    app: concord
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: concord
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concord
  namespace: concord
  labels:
    app: concord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concord
  template:
    metadata:
      labels:
        app: concord
    spec:
      containers:
        - name: concord
          image: localhost:5000/concord-fastapi_concord:latest
          command: ['/start-reload.sh']
          env:
            - name: PORT
              value: "80"
            - name: MODULE_NAME
              value: src.main
            - name: BACKEND_URL
              value: http://localhost:81
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONIOENCODING
              value: "UTF-8"
          ports:
          - name: api
            containerPort: 80
          volumeMounts:
            - name: local-repo
              mountPath: /app/src/
              subPath: concord/src/
              readOnly: true
        - name: backend
          image: localhost:5000/concord-fastapi_backend:latest
          command: ['/start-reload.sh']
          env:
            - name: PORT
              value: "81"
            - name: MODULE_NAME
              value: src.main
          ports:
          - name: api
            containerPort: 81
          volumeMounts:
            - name: local-repo
              mountPath: /app/src/
              subPath: backend/src/
              readOnly: true
      volumes:
        - name: local-repo
          hostPath:
            path: /concord-fastapi
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: concord-ingress
  namespace: concord
spec:
  prefix: /
  service: concord:80
  timeout_ms: 40000