bases:
- ../base

images:
- name: DOCKER_REGISTRY/concord-db
  newName: matzhaugen/concord-db
- name: DOCKER_REGISTRY/concord
  newName: matzhaugen/concord
  newTag: "1"
- name: DOCKER_REGISTRY/starlette-backend
  newName: matzhaugen/starlette-backend
