apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-repo-pv
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /Users/matzhaugen/projects/concord-fastapi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pool-wi7gvdp4c-3vi34
          - pool-wi7gvdp4c-3vi3i
          - pool-wi7gvdp4c-3vi3v
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-repo-pvc
  namespace: concord
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi